NFS_CORE_PARAM {
    Protocols = 4;
    Enable_UDP = false;
    Enable_NLM = false;
    Enable_RQUOTA = false;
}

EXPORT {
    Export_Id = 1;
    Path = /workspace/nfs-rootfs;
    Pseudo = /;
    Protocols = 4;
    Transports = TCP;
    SecType = sys;
    Access_Type = None;

    CLIENT {
        Clients = 192.168.1.2;
        Protocols = 4;
        Access_Type = RW;
        Squash = No_Root_Squash;
    }

    FSAL {
        Name = VFS;
    }
}

DIRECTORY_SERVICES {
    DomainName = localdomain;
    Idmapped_User_Time_Validity = 1800;
    Idmapped_Group_Time_Validity = 1800;
}

NFS_KRB5 {
    Active_krb5 = false;
}

NFSV4 {
    Only_Numeric_Owners = true;
    Allow_Numeric_Owners = true;
}
