NFS_CORE_PARAM {
    Protocols = 4;
    Enable_UDP = false;
    Enable_NLM = false;
    Enable_RQUOTA = false;
}

EXPORT {
    Export_Id = 1;
    Path = /workspace/nfs-rootfs;
    Pseudo = /;
    Protocols = 4;
    Transports = TCP;
    SecType = sys;
    Access_Type = None;
    CLIENT {
        Clients = 192.168.1.2;
        Access_Type = RW;
        Squash = No_Root_Squash;
    }
    FSAL {
        Name = VFS;
    }
}
